import { Inter } from "next/font/google";
import "./globals.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../app/library/theme/theme';
import localFont from 'next/font/local'


import Provider from "./library/provider/Provider";


const inter = Inter({ subsets: ["latin"] });

const vazir_font = localFont({ src: '../public/fonts/Vazir.woff2' })


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider theme={theme}>
      <AppRouterCacheProvider options={{ key: 'css' }}>
        <Provider>
          <html lang="fa-IR" dir="rtl">
            <body className={`${inter.className} ${vazir_font.className}`}>
              {children}
            </body>
          </html>
        </Provider>
      </AppRouterCacheProvider>
    </ThemeProvider>
  );
}
